remote_theme: just-the-docs/just-the-docs

title: SYSU-ARCH 
description: Welcome to SYSU-ARCH's homepage
baseurl: "/SYSU-ARCH"
url: "https://gty111.github.io"

logo: "/assets/images/ARSYSU.png"

callouts_level: quiet
callouts:
  highlight:
    color: green
  question:
    color: red

footer_content: "Supported by <a href=\"https://gty111.github.io\">TianYu GUO</a>"

color_scheme: light
